# Generated by Django 4.2 on 2023-05-27 18:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminConfig",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("captcha_site_key", models.TextField(blank=True, null=True)),
                ("captcha_secret_key", models.TextField(blank=True, null=True)),
                ("default_traffic", models.PositiveIntegerField(default=10)),
                (
                    "default_configs",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
            options={
                "verbose_name": "Admin Config",
                "verbose_name_plural": "Admin Config",
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OcservGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("configs", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "Ocserv Group",
                "verbose_name_plural": "Ocserv Groups",
            },
        ),
        migrations.CreateModel(
            name="OcservUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, unique=True)),
                ("password", models.CharField(blank=True, max_length=32, null=True)),
                ("active", models.BooleanField(default=False)),
                ("create", models.DateField(auto_now_add=True)),
                ("expire_date", models.DateField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "traffic",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "free"), (2, "monthly"), (3, "totally")], default=2
                    ),
                ),
                ("default_traffic", models.PositiveIntegerField(default=0)),
                ("tx", models.PositiveIntegerField(default=0)),
                ("rx", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ocservgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocserv User",
                "verbose_name_plural": "Ocserv Users",
            },
        ),
        migrations.CreateModel(
            name="MonthlyTrafficStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=2023)),
                ("month", models.PositiveSmallIntegerField(default=1)),
                ("tx", models.PositiveIntegerField(default=0)),
                ("rx", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="app.ocservuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Traffic Stat",
                "verbose_name_plural": "Monthly Traffic Stats",
            },
        ),
    ]
