# Generated by Django 4.2 on 2023-07-06 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
