# Generated by Django 4.2 on 2024-03-12 08:09
import logging

from django.db import migrations, models


def forward_func(apps, schema_editor):
    try:
        new_config_model = apps.get_model("app", "adminpanelconfiguration")
        old_config_model = apps.get_model("app", "adminconfig")
        obj = old_config_model.objects.last()
        old_config_model.is_superuser = True
        old_config_model.user.save()
        if not new_config_model.objects.exists():
            new_config_model.objects.create(
                captcha_site_key=obj.captcha_site_key,
                captcha_secret_key=obj.captcha_secret_key,
                default_traffic=obj.default_traffic,
                default_configs=obj.default_configs,
            )
            old_config_model.is_superuser = True
            old_config_model.user.save()
    except Exception as e:
        logging.info("new database detected")


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_adminconfig_uu_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPanelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captcha_site_key", models.TextField(blank=True, null=True)),
                ("captcha_secret_key", models.TextField(blank=True, null=True)),
                ("default_traffic", models.PositiveIntegerField(default=10)),
                (
                    "default_configs",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
            options={
                "verbose_name": "Admin Panel Configuration",
                "verbose_name_plural": "Admin Panel Configurations",
            },
        ),
        migrations.RunPython(forward_func),
    ]
