# Generated by Django 4.2 on 2024-03-12 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_adminpanelconfiguration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminConfig",
        ),
    ]
