FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y --no-install-recommends ocserv gnutls-bin build-essential
RUN apt-get install -y --no-install-recommends gettext-base iptables cron openssl sudo
RUN apt-get install -y --no-install-recommends python3 python3-dev
RUN apt install -y --no-install-recommends python3-pip

# backend installation
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ARG HOST
ARG DEBUG
ARG CORS_ALLOWED
RUN mkdir -p /app
WORKDIR /app
COPY back-end/ .
RUN mkdir -p db
# RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

# ocserv installation
COPY configs/services_pack.sh /services.sh
COPY configs/entrypoint_ocserv.sh /entrypoint.sh
RUN chmod +x /services.sh /entrypoint.sh
RUN echo net.ipv4.ip_forward=1 | tee -a /etc/sysctl.conf && sysctl -p
EXPOSE 443/tcp 443/udp
VOLUME ["/etc/ocserv", "/app/db"]
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/services.sh"]
