FROM ubuntu:24.04

RUN apt update && apt install -y --no-install-recommends \
    ocserv gnutls-bin build-essential gettext-base iptables \
    cron openssl sudo python3 python3-dev python3-pip python3-venv && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# ARG HOST
# ARG DEBUG
# ARG CORS_ALLOWED

RUN mkdir -p /app /opt/venv /app/db

WORKDIR /app

COPY back-end/requirements.txt .

RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --upgrade pip setuptools && \
    /opt/venv/bin/pip install -r requirements.txt
    
ENV PATH="/opt/venv/bin:$PATH"

COPY back-end/ /app

COPY configs/services_pack.sh /services.sh

COPY configs/entrypoint_ocserv.sh /entrypoint.sh

RUN chmod +x /services.sh /entrypoint.sh && echo net.ipv4.ip_forward=1 | tee -a /etc/sysctl.conf && sysctl 

EXPOSE 443/tcp 443/udp
VOLUME ["/etc/ocserv", "/app/db"]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/services.sh"]
