FROM ubuntu:24.04

RUN apt update
RUN apt install -y --no-install-recommends ocserv gnutls-bin build-essential
RUN apt install -y --no-install-recommends gettext-base iptables cron openssl sudo
RUN apt install -y --no-install-recommends python3 python3-dev
RUN apt install -y --no-install-recommends python3-pip python3-venv

# backend installation
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ARG HOST
ARG DEBUG
ARG CORS_ALLOWED
RUN mkdir -p /app
WORKDIR /app
COPY back-end/ .
RUN mkdir -p db
# RUN python3 -m pip install --upgrade pip
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install --upgrade setuptools

# ocserv installation
COPY configs/services_pack.sh /services.sh
COPY configs/entrypoint_ocserv.sh /entrypoint.sh
RUN chmod +x /services.sh /entrypoint.sh
RUN echo net.ipv4.ip_forward=1 | tee -a /etc/sysctl.conf && sysctl -p
EXPOSE 443/tcp 443/udp
VOLUME ["/etc/ocserv", "/app/db"]
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/services.sh"]
