FROM golang:1.20

WORKDIR /usr/src/app

COPY ./monitor/go.mod ./monitor/go.sum .

RUN go mod download && go mod verify

COPY ./monitor/ .

RUN go build -v -o /usr/local/bin/app ./...

EXPOSE 8080

CMD ["app"]