/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsUser
 */
export interface ModelsUser {
    /**
     * 
     * @type {number}
     * @memberof ModelsUser
     */
    '_': number;
    /**
     * LastLogin *time.Time `json:\"last_login\"  validate:\"required\"`
     * @type {string}
     * @memberof ModelsUser
     */
    'createdAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsUser
     */
    'is_admin': boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    'uid': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    'username': string;
}

