/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OcservUserCreateOcservUserData
 */
export interface OcservUserCreateOcservUserData {
    /**
     * 
     * @type {string}
     * @memberof OcservUserCreateOcservUserData
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcservUserCreateOcservUserData
     */
    'expire_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcservUserCreateOcservUserData
     */
    'group': string;
    /**
     * 
     * @type {string}
     * @memberof OcservUserCreateOcservUserData
     */
    'password': string;
    /**
     * 10 GiB
     * @type {number}
     * @memberof OcservUserCreateOcservUserData
     */
    'traffic_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof OcservUserCreateOcservUserData
     */
    'traffic_type': OcservUserCreateOcservUserDataTrafficTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof OcservUserCreateOcservUserData
     */
    'username': string;
}

export const OcservUserCreateOcservUserDataTrafficTypeEnum = {
    FREE: 'Free',
    MONTHLY_TRANSMIT: 'MonthlyTransmit',
    MONTHLY_RECEIVE: 'MonthlyReceive',
    TOTALLY_TRANSMIT: 'TotallyTransmit',
    TOTALLY_RECEIVE: 'TotallyReceive'
} as const;

export type OcservUserCreateOcservUserDataTrafficTypeEnum = typeof OcservUserCreateOcservUserDataTrafficTypeEnum[keyof typeof OcservUserCreateOcservUserDataTrafficTypeEnum];


