/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RequestMeta
 */
export interface RequestMeta {
    /**
     * 
     * @type {number}
     * @memberof RequestMeta
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof RequestMeta
     */
    'page_size': number;
    /**
     * 
     * @type {number}
     * @memberof RequestMeta
     */
    'total_records': number;
}

