# Generated by Django 3.2 on 2021-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcservUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_username', models.CharField(max_length=16)),
                ('oc_password', models.CharField(max_length=32)),
                ('oc_active', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ocserv User',
                'verbose_name_plural': 'Ocserv Users',
                'ordering': ['-create'],
            },
        ),
    ]
