# Generated by Django 3.2 on 2021-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocservuser',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocservuser',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
