/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LogUsersLogsResponse } from '../models';
// @ts-ignore
import type { MiddlewaresPermissionDenied } from '../models';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * LogsApi - axios parameter creator
 * @export
 */
export const LogsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List of logs
         * @summary List of logs
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {LogsAuditGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {string} [uid] Search User by UID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logsAuditGet: async (authorization: string, page?: number, size?: number, order?: string, sort?: LogsAuditGetSortEnum, uid?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('logsAuditGet', 'authorization', authorization)
            const localVarPath = `/logs/audit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (uid !== undefined) {
                localVarQueryParameter['uid'] = uid;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LogsApi - functional programming interface
 * @export
 */
export const LogsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LogsApiAxiosParamCreator(configuration)
    return {
        /**
         * List of logs
         * @summary List of logs
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {LogsAuditGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {string} [uid] Search User by UID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logsAuditGet(authorization: string, page?: number, size?: number, order?: string, sort?: LogsAuditGetSortEnum, uid?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LogUsersLogsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logsAuditGet(authorization, page, size, order, sort, uid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LogsApi.logsAuditGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LogsApi - factory interface
 * @export
 */
export const LogsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LogsApiFp(configuration)
    return {
        /**
         * List of logs
         * @summary List of logs
         * @param {LogsApiLogsAuditGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logsAuditGet(requestParameters: LogsApiLogsAuditGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<LogUsersLogsResponse> {
            return localVarFp.logsAuditGet(requestParameters.authorization, requestParameters.page, requestParameters.size, requestParameters.order, requestParameters.sort, requestParameters.uid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for logsAuditGet operation in LogsApi.
 * @export
 * @interface LogsApiLogsAuditGetRequest
 */
export interface LogsApiLogsAuditGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof LogsApiLogsAuditGet
     */
    readonly authorization: string

    /**
     * Page number, starting from 1
     * @type {number}
     * @memberof LogsApiLogsAuditGet
     */
    readonly page?: number

    /**
     * Number of items per page
     * @type {number}
     * @memberof LogsApiLogsAuditGet
     */
    readonly size?: number

    /**
     * Field to order by
     * @type {string}
     * @memberof LogsApiLogsAuditGet
     */
    readonly order?: string

    /**
     * Sort order, either ASC or DESC
     * @type {'ASC' | 'DESC'}
     * @memberof LogsApiLogsAuditGet
     */
    readonly sort?: LogsAuditGetSortEnum

    /**
     * Search User by UID
     * @type {string}
     * @memberof LogsApiLogsAuditGet
     */
    readonly uid?: string
}

/**
 * LogsApi - object-oriented interface
 * @export
 * @class LogsApi
 * @extends {BaseAPI}
 */
export class LogsApi extends BaseAPI {
    /**
     * List of logs
     * @summary List of logs
     * @param {LogsApiLogsAuditGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LogsApi
     */
    public logsAuditGet(requestParameters: LogsApiLogsAuditGetRequest, options?: RawAxiosRequestConfig) {
        return LogsApiFp(this.configuration).logsAuditGet(requestParameters.authorization, requestParameters.page, requestParameters.size, requestParameters.order, requestParameters.sort, requestParameters.uid, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const LogsAuditGetSortEnum = {
    ASC: 'ASC',
    DESC: 'DESC'
} as const;
export type LogsAuditGetSortEnum = typeof LogsAuditGetSortEnum[keyof typeof LogsAuditGetSortEnum];
