/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { ModelsOcservGroup } from '../models';
// @ts-ignore
import type { OcservGroupCreateOcservGroupData } from '../models';
// @ts-ignore
import type { OcservGroupOcservGroupsResponse } from '../models';
// @ts-ignore
import type { OcservGroupUpdateOcservGroupData } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * OcservGroupsApi - axios parameter creator
 * @export
 */
export const OcservGroupsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ocserv Defaults Group config
         * @summary Ocserv Defaults Group config
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsDefaultsGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsDefaultsGet', 'authorization', authorization)
            const localVarPath = `/ocserv/groups/defaults`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update Ocserv Defaults Group
         * @summary Update Ocserv Defaults Group
         * @param {string} authorization Bearer TOKEN
         * @param {OcservGroupUpdateOcservGroupData} request ocserv group default data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsDefaultsPatch: async (authorization: string, request: OcservGroupUpdateOcservGroupData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsDefaultsPatch', 'authorization', authorization)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('ocservGroupsDefaultsPatch', 'request', request)
            const localVarPath = `/ocserv/groups/defaults`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List of Ocserv groups
         * @summary List of Ocserv groups
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {OcservGroupsGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsGet: async (authorization: string, page?: number, size?: number, order?: string, sort?: OcservGroupsGetSortEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsGet', 'authorization', authorization)
            const localVarPath = `/ocserv/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ocserv Group delete
         * @summary Ocserv Group delete
         * @param {string} authorization Bearer TOKEN
         * @param {number} id Ocserv Group ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsIdDelete: async (authorization: string, id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsIdDelete', 'authorization', authorization)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ocservGroupsIdDelete', 'id', id)
            const localVarPath = `/ocserv/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ocserv Group update
         * @summary Ocserv Group update
         * @param {string} authorization Bearer TOKEN
         * @param {number} id Ocserv Group ID
         * @param {OcservGroupUpdateOcservGroupData} request ocserv group create data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsIdPatch: async (authorization: string, id: number, request: OcservGroupUpdateOcservGroupData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsIdPatch', 'authorization', authorization)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ocservGroupsIdPatch', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('ocservGroupsIdPatch', 'request', request)
            const localVarPath = `/ocserv/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List of Ocserv group names
         * @summary List of Ocserv group names
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsLookupGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsLookupGet', 'authorization', authorization)
            const localVarPath = `/ocserv/groups/lookup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ocserv Group creation
         * @summary Ocserv Group creation
         * @param {string} authorization Bearer TOKEN
         * @param {OcservGroupCreateOcservGroupData} request ocserv group create data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsPost: async (authorization: string, request: OcservGroupCreateOcservGroupData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsPost', 'authorization', authorization)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('ocservGroupsPost', 'request', request)
            const localVarPath = `/ocserv/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OcservGroupsApi - functional programming interface
 * @export
 */
export const OcservGroupsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OcservGroupsApiAxiosParamCreator(configuration)
    return {
        /**
         * Ocserv Defaults Group config
         * @summary Ocserv Defaults Group config
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsDefaultsGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsDefaultsGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservGroupsApi.ocservGroupsDefaultsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update Ocserv Defaults Group
         * @summary Update Ocserv Defaults Group
         * @param {string} authorization Bearer TOKEN
         * @param {OcservGroupUpdateOcservGroupData} request ocserv group default data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsDefaultsPatch(authorization: string, request: OcservGroupUpdateOcservGroupData, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsDefaultsPatch(authorization, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservGroupsApi.ocservGroupsDefaultsPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List of Ocserv groups
         * @summary List of Ocserv groups
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {OcservGroupsGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsGet(authorization: string, page?: number, size?: number, order?: string, sort?: OcservGroupsGetSortEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OcservGroupOcservGroupsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsGet(authorization, page, size, order, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservGroupsApi.ocservGroupsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ocserv Group delete
         * @summary Ocserv Group delete
         * @param {string} authorization Bearer TOKEN
         * @param {number} id Ocserv Group ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsIdDelete(authorization: string, id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsIdDelete(authorization, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservGroupsApi.ocservGroupsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ocserv Group update
         * @summary Ocserv Group update
         * @param {string} authorization Bearer TOKEN
         * @param {number} id Ocserv Group ID
         * @param {OcservGroupUpdateOcservGroupData} request ocserv group create data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsIdPatch(authorization: string, id: number, request: OcservGroupUpdateOcservGroupData, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsOcservGroup>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsIdPatch(authorization, id, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservGroupsApi.ocservGroupsIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List of Ocserv group names
         * @summary List of Ocserv group names
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsLookupGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsLookupGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservGroupsApi.ocservGroupsLookupGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ocserv Group creation
         * @summary Ocserv Group creation
         * @param {string} authorization Bearer TOKEN
         * @param {OcservGroupCreateOcservGroupData} request ocserv group create data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsPost(authorization: string, request: OcservGroupCreateOcservGroupData, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsOcservGroup>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsPost(authorization, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservGroupsApi.ocservGroupsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OcservGroupsApi - factory interface
 * @export
 */
export const OcservGroupsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OcservGroupsApiFp(configuration)
    return {
        /**
         * Ocserv Defaults Group config
         * @summary Ocserv Defaults Group config
         * @param {OcservGroupsApiOcservGroupsDefaultsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsDefaultsGet(requestParameters: OcservGroupsApiOcservGroupsDefaultsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.ocservGroupsDefaultsGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Update Ocserv Defaults Group
         * @summary Update Ocserv Defaults Group
         * @param {OcservGroupsApiOcservGroupsDefaultsPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsDefaultsPatch(requestParameters: OcservGroupsApiOcservGroupsDefaultsPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.ocservGroupsDefaultsPatch(requestParameters.authorization, requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * List of Ocserv groups
         * @summary List of Ocserv groups
         * @param {OcservGroupsApiOcservGroupsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsGet(requestParameters: OcservGroupsApiOcservGroupsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<OcservGroupOcservGroupsResponse> {
            return localVarFp.ocservGroupsGet(requestParameters.authorization, requestParameters.page, requestParameters.size, requestParameters.order, requestParameters.sort, options).then((request) => request(axios, basePath));
        },
        /**
         * Ocserv Group delete
         * @summary Ocserv Group delete
         * @param {OcservGroupsApiOcservGroupsIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsIdDelete(requestParameters: OcservGroupsApiOcservGroupsIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.ocservGroupsIdDelete(requestParameters.authorization, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Ocserv Group update
         * @summary Ocserv Group update
         * @param {OcservGroupsApiOcservGroupsIdPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsIdPatch(requestParameters: OcservGroupsApiOcservGroupsIdPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModelsOcservGroup> {
            return localVarFp.ocservGroupsIdPatch(requestParameters.authorization, requestParameters.id, requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * List of Ocserv group names
         * @summary List of Ocserv group names
         * @param {OcservGroupsApiOcservGroupsLookupGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsLookupGet(requestParameters: OcservGroupsApiOcservGroupsLookupGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.ocservGroupsLookupGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Ocserv Group creation
         * @summary Ocserv Group creation
         * @param {OcservGroupsApiOcservGroupsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsPost(requestParameters: OcservGroupsApiOcservGroupsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModelsOcservGroup> {
            return localVarFp.ocservGroupsPost(requestParameters.authorization, requestParameters.request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for ocservGroupsDefaultsGet operation in OcservGroupsApi.
 * @export
 * @interface OcservGroupsApiOcservGroupsDefaultsGetRequest
 */
export interface OcservGroupsApiOcservGroupsDefaultsGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservGroupsApiOcservGroupsDefaultsGet
     */
    readonly authorization: string
}

/**
 * Request parameters for ocservGroupsDefaultsPatch operation in OcservGroupsApi.
 * @export
 * @interface OcservGroupsApiOcservGroupsDefaultsPatchRequest
 */
export interface OcservGroupsApiOcservGroupsDefaultsPatchRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservGroupsApiOcservGroupsDefaultsPatch
     */
    readonly authorization: string

    /**
     * ocserv group default data
     * @type {OcservGroupUpdateOcservGroupData}
     * @memberof OcservGroupsApiOcservGroupsDefaultsPatch
     */
    readonly request: OcservGroupUpdateOcservGroupData
}

/**
 * Request parameters for ocservGroupsGet operation in OcservGroupsApi.
 * @export
 * @interface OcservGroupsApiOcservGroupsGetRequest
 */
export interface OcservGroupsApiOcservGroupsGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservGroupsApiOcservGroupsGet
     */
    readonly authorization: string

    /**
     * Page number, starting from 1
     * @type {number}
     * @memberof OcservGroupsApiOcservGroupsGet
     */
    readonly page?: number

    /**
     * Number of items per page
     * @type {number}
     * @memberof OcservGroupsApiOcservGroupsGet
     */
    readonly size?: number

    /**
     * Field to order by
     * @type {string}
     * @memberof OcservGroupsApiOcservGroupsGet
     */
    readonly order?: string

    /**
     * Sort order, either ASC or DESC
     * @type {'ASC' | 'DESC'}
     * @memberof OcservGroupsApiOcservGroupsGet
     */
    readonly sort?: OcservGroupsGetSortEnum
}

/**
 * Request parameters for ocservGroupsIdDelete operation in OcservGroupsApi.
 * @export
 * @interface OcservGroupsApiOcservGroupsIdDeleteRequest
 */
export interface OcservGroupsApiOcservGroupsIdDeleteRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservGroupsApiOcservGroupsIdDelete
     */
    readonly authorization: string

    /**
     * Ocserv Group ID
     * @type {number}
     * @memberof OcservGroupsApiOcservGroupsIdDelete
     */
    readonly id: number
}

/**
 * Request parameters for ocservGroupsIdPatch operation in OcservGroupsApi.
 * @export
 * @interface OcservGroupsApiOcservGroupsIdPatchRequest
 */
export interface OcservGroupsApiOcservGroupsIdPatchRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservGroupsApiOcservGroupsIdPatch
     */
    readonly authorization: string

    /**
     * Ocserv Group ID
     * @type {number}
     * @memberof OcservGroupsApiOcservGroupsIdPatch
     */
    readonly id: number

    /**
     * ocserv group create data
     * @type {OcservGroupUpdateOcservGroupData}
     * @memberof OcservGroupsApiOcservGroupsIdPatch
     */
    readonly request: OcservGroupUpdateOcservGroupData
}

/**
 * Request parameters for ocservGroupsLookupGet operation in OcservGroupsApi.
 * @export
 * @interface OcservGroupsApiOcservGroupsLookupGetRequest
 */
export interface OcservGroupsApiOcservGroupsLookupGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservGroupsApiOcservGroupsLookupGet
     */
    readonly authorization: string
}

/**
 * Request parameters for ocservGroupsPost operation in OcservGroupsApi.
 * @export
 * @interface OcservGroupsApiOcservGroupsPostRequest
 */
export interface OcservGroupsApiOcservGroupsPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservGroupsApiOcservGroupsPost
     */
    readonly authorization: string

    /**
     * ocserv group create data
     * @type {OcservGroupCreateOcservGroupData}
     * @memberof OcservGroupsApiOcservGroupsPost
     */
    readonly request: OcservGroupCreateOcservGroupData
}

/**
 * OcservGroupsApi - object-oriented interface
 * @export
 * @class OcservGroupsApi
 * @extends {BaseAPI}
 */
export class OcservGroupsApi extends BaseAPI {
    /**
     * Ocserv Defaults Group config
     * @summary Ocserv Defaults Group config
     * @param {OcservGroupsApiOcservGroupsDefaultsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservGroupsApi
     */
    public ocservGroupsDefaultsGet(requestParameters: OcservGroupsApiOcservGroupsDefaultsGetRequest, options?: RawAxiosRequestConfig) {
        return OcservGroupsApiFp(this.configuration).ocservGroupsDefaultsGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update Ocserv Defaults Group
     * @summary Update Ocserv Defaults Group
     * @param {OcservGroupsApiOcservGroupsDefaultsPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservGroupsApi
     */
    public ocservGroupsDefaultsPatch(requestParameters: OcservGroupsApiOcservGroupsDefaultsPatchRequest, options?: RawAxiosRequestConfig) {
        return OcservGroupsApiFp(this.configuration).ocservGroupsDefaultsPatch(requestParameters.authorization, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List of Ocserv groups
     * @summary List of Ocserv groups
     * @param {OcservGroupsApiOcservGroupsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservGroupsApi
     */
    public ocservGroupsGet(requestParameters: OcservGroupsApiOcservGroupsGetRequest, options?: RawAxiosRequestConfig) {
        return OcservGroupsApiFp(this.configuration).ocservGroupsGet(requestParameters.authorization, requestParameters.page, requestParameters.size, requestParameters.order, requestParameters.sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ocserv Group delete
     * @summary Ocserv Group delete
     * @param {OcservGroupsApiOcservGroupsIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservGroupsApi
     */
    public ocservGroupsIdDelete(requestParameters: OcservGroupsApiOcservGroupsIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return OcservGroupsApiFp(this.configuration).ocservGroupsIdDelete(requestParameters.authorization, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ocserv Group update
     * @summary Ocserv Group update
     * @param {OcservGroupsApiOcservGroupsIdPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservGroupsApi
     */
    public ocservGroupsIdPatch(requestParameters: OcservGroupsApiOcservGroupsIdPatchRequest, options?: RawAxiosRequestConfig) {
        return OcservGroupsApiFp(this.configuration).ocservGroupsIdPatch(requestParameters.authorization, requestParameters.id, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List of Ocserv group names
     * @summary List of Ocserv group names
     * @param {OcservGroupsApiOcservGroupsLookupGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservGroupsApi
     */
    public ocservGroupsLookupGet(requestParameters: OcservGroupsApiOcservGroupsLookupGetRequest, options?: RawAxiosRequestConfig) {
        return OcservGroupsApiFp(this.configuration).ocservGroupsLookupGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ocserv Group creation
     * @summary Ocserv Group creation
     * @param {OcservGroupsApiOcservGroupsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservGroupsApi
     */
    public ocservGroupsPost(requestParameters: OcservGroupsApiOcservGroupsPostRequest, options?: RawAxiosRequestConfig) {
        return OcservGroupsApiFp(this.configuration).ocservGroupsPost(requestParameters.authorization, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const OcservGroupsGetSortEnum = {
    ASC: 'ASC',
    DESC: 'DESC'
} as const;
export type OcservGroupsGetSortEnum = typeof OcservGroupsGetSortEnum[keyof typeof OcservGroupsGetSortEnum];
