// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GoogleCaptchaInterface is an autogenerated mock type for the GoogleCaptchaInterface type
type GoogleCaptchaInterface struct {
	mock.Mock
}

// IsValid provides a mock function with no fields
func (_m *GoogleCaptchaInterface) IsValid() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetSecretKey provides a mock function with given fields: secretKey
func (_m *GoogleCaptchaInterface) SetSecretKey(secretKey string) {
	_m.Called(secretKey)
}

// Verify provides a mock function with given fields: token
func (_m *GoogleCaptchaInterface) Verify(token string) {
	_m.Called(token)
}

// NewGoogleCaptchaInterface creates a new instance of GoogleCaptchaInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleCaptchaInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleCaptchaInterface {
	mock := &GoogleCaptchaInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
