// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "ocserv-bakend/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// OcGroupApiRepositoryInterface is an autogenerated mock type for the OcGroupApiRepositoryInterface type
type OcGroupApiRepositoryInterface struct {
	mock.Mock
}

// CreateGroupApi provides a mock function with given fields: name, config
func (_m *OcGroupApiRepositoryInterface) CreateGroupApi(name string, config *models.OcservGroupConfig) error {
	ret := _m.Called(name, config)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupApi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *models.OcservGroupConfig) error); ok {
		r0 = rf(name, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOcGroupApiRepositoryInterface creates a new instance of OcGroupApiRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOcGroupApiRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OcGroupApiRepositoryInterface {
	mock := &OcGroupApiRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
