// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "ocserv-bakend/internal/models"

	mock "github.com/stretchr/testify/mock"

	request "ocserv-bakend/pkg/request"
)

// OcservGroupRepositoryInterface is an autogenerated mock type for the OcservGroupRepositoryInterface type
type OcservGroupRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, ocservGroup
func (_m *OcservGroupRepositoryInterface) Create(ctx context.Context, ocservGroup *models.OcservGroup) (*models.OcservGroup, error) {
	ret := _m.Called(ctx, ocservGroup)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.OcservGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.OcservGroup) (*models.OcservGroup, error)); ok {
		return rf(ctx, ocservGroup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.OcservGroup) *models.OcservGroup); ok {
		r0 = rf(ctx, ocservGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OcservGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.OcservGroup) error); ok {
		r1 = rf(ctx, ocservGroup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Groups provides a mock function with given fields: ctx, pagination
func (_m *OcservGroupRepositoryInterface) Groups(ctx context.Context, pagination *request.Pagination) (*[]models.OcservGroup, int64, error) {
	ret := _m.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for Groups")
	}

	var r0 *[]models.OcservGroup
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.Pagination) (*[]models.OcservGroup, int64, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.Pagination) *[]models.OcservGroup); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.OcservGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.Pagination) int64); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *request.Pagination) error); ok {
		r2 = rf(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewOcservGroupRepositoryInterface creates a new instance of OcservGroupRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOcservGroupRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OcservGroupRepositoryInterface {
	mock := &OcservGroupRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
