// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OcUserApiRepositoryInterface is an autogenerated mock type for the OcUserApiRepositoryInterface type
type OcUserApiRepositoryInterface struct {
	mock.Mock
}

// CreateApi provides a mock function with given fields: group, username, password
func (_m *OcUserApiRepositoryInterface) CreateApi(group string, username string, password string) error {
	ret := _m.Called(group, username, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateApi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(group, username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteApi provides a mock function with given fields: username
func (_m *OcUserApiRepositoryInterface) DeleteApi(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LockApi provides a mock function with given fields: username
func (_m *OcUserApiRepositoryInterface) LockApi(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for LockApi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnLockApi provides a mock function with given fields: username
func (_m *OcUserApiRepositoryInterface) UnLockApi(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for UnLockApi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOcUserApiRepositoryInterface creates a new instance of OcUserApiRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOcUserApiRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OcUserApiRepositoryInterface {
	mock := &OcUserApiRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
