/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuditLogAuditLog
 */
export interface AuditLogAuditLog {
    /**
     * action and reason json string
     * @type {string}
     * @memberof AuditLogAuditLog
     */
    'action'?: string;
    /**
     * Full JSON or JSON diff
     * @type {string}
     * @memberof AuditLogAuditLog
     */
    'changes'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditLogAuditLog
     */
    'created_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof AuditLogAuditLog
     */
    'id'?: number;
    /**
     * e.g., \"OcservUser\"
     * @type {string}
     * @memberof AuditLogAuditLog
     */
    'model'?: string;
    /**
     * e.g., UID or primary key
     * @type {string}
     * @memberof AuditLogAuditLog
     */
    'model_id'?: string;
    /**
     * ULID or user identifier
     * @type {string}
     * @memberof AuditLogAuditLog
     */
    'user_uid'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditLogAuditLog
     */
    'username'?: string;
}

