/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HomeCurrentStats
 */
export interface HomeCurrentStats {
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'Authentication failures'?: number;
    /**
     * 
     * @type {string}
     * @memberof HomeCurrentStats
     */
    'Average auth time'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeCurrentStats
     */
    'Average session time'?: string;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'Closed due to error sessions'?: number;
    /**
     * 
     * @type {string}
     * @memberof HomeCurrentStats
     */
    'Last stats reset'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeCurrentStats
     */
    'Max auth time'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeCurrentStats
     */
    'Max session time'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeCurrentStats
     */
    'RX'?: string;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'Sessions handled'?: number;
    /**
     * 
     * @type {string}
     * @memberof HomeCurrentStats
     */
    'TX'?: string;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'Timed out (idle) sessions'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'Timed out sessions'?: number;
    /**
     * 
     * @type {string}
     * @memberof HomeCurrentStats
     */
    '_Last stats reset'?: string;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'raw_avg_auth_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'raw_avg_session_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'raw_last_stats_reset'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'raw_max_auth_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'raw_max_session_time'?: number;
    /**
     * raw fields if you want
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'raw_rx'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeCurrentStats
     */
    'raw_tx'?: number;
}

