/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HomeGeneralInfo
 */
export interface HomeGeneralInfo {
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'Active sessions'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'IPs in ban list'?: number;
    /**
     * 
     * @type {string}
     * @memberof HomeGeneralInfo
     */
    'Median latency'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeGeneralInfo
     */
    'STDEV latency'?: string;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'Sec-mod PID'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'Sec-mod instance count'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'Server PID'?: number;
    /**
     * 
     * @type {string}
     * @memberof HomeGeneralInfo
     */
    'Status'?: string;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'Total authentication failures'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'Total sessions'?: number;
    /**
     * 
     * @type {string}
     * @memberof HomeGeneralInfo
     */
    'Up since'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeGeneralInfo
     */
    '_Up since'?: string;
    /**
     * raw fields if you want
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'raw_median_latency'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'raw_stdev_latency'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'raw_up_since'?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeGeneralInfo
     */
    'uptime'?: number;
}

