/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsIroute
 */
export interface ModelsIroute {
    /**
     * 
     * @type {string}
     * @memberof ModelsIroute
     */
    'Device'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsIroute
     */
    'ID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsIroute
     */
    'IP'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsIroute
     */
    'Username'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsIroute
     */
    'iRoutes'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsIroute
     */
    'vhost'?: string;
}

