/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsIPBan
 */
export interface ModelsIPBan {
    /**
     * 
     * @type {string}
     * @memberof ModelsIPBan
     */
    'IP'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsIPBan
     */
    'Score'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsIPBan
     */
    'Since'?: string;
    /**
     * maps to \"_Since\" in JSON
     * @type {string}
     * @memberof ModelsIPBan
     */
    '_Since'?: string;
}

