/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsOcservUserConfig
 */
export interface ModelsOcservUserConfig {
    /**
     * Text message shown to users when they connect to the VPN. Example: \'Welcome to the company VPN!\'
     * @type {string}
     * @memberof ModelsOcservUserConfig
     */
    'banner'?: string;
    /**
     * Comma-separated list of DNS servers to assign to the user. Example: \'8.8.8.8,1.1.1.1\'
     * @type {Array<string>}
     * @memberof ModelsOcservUserConfig
     */
    'dns'?: Array<string>;
    /**
     * Static IPv4 address to assign to the user. Example: \'192.168.100.10\'
     * @type {string}
     * @memberof ModelsOcservUserConfig
     */
    'explicit-ipv4'?: string;
    /**
     * Time in seconds before disconnecting idle users. Example: 600
     * @type {number}
     * @memberof ModelsOcservUserConfig
     */
    'idle-timeout'?: number;
    /**
     * The pool of addresses from which to assign to the user. Example: \'192.168.1.0/24\'
     * @type {string}
     * @memberof ModelsOcservUserConfig
     */
    'ipv4-network'?: string;
    /**
     * Internal route available only via VPN. Example: \'10.0.0.0/8\'
     * @type {string}
     * @memberof ModelsOcservUserConfig
     */
    'iroute'?: string;
    /**
     * Idle timeout in seconds for mobile users. Example: 900
     * @type {number}
     * @memberof ModelsOcservUserConfig
     */
    'mobile-idle-timeout'?: number;
    /**
     * NetBIOS Name Servers (WINS) for Windows clients. Example: \'192.168.1.1\'
     * @type {string}
     * @memberof ModelsOcservUserConfig
     */
    'nbns'?: string;
    /**
     * List of networks to exclude from VPN routing. Example: [\'192.168.0.0/16\', \'10.0.0.0/8\']
     * @type {Array<string>}
     * @memberof ModelsOcservUserConfig
     */
    'no-route'?: Array<string>;
    /**
     * Rekey time in seconds; triggers key renegotiation. Example: 86400 for 24 hours
     * @type {number}
     * @memberof ModelsOcservUserConfig
     */
    'rekey-time'?: number;
    /**
     * Comma-separated list of allowed or blocked ports/protocols. Supports \'tcp(port)\', \'udp(port)\', \'icmp()\', \'icmpv6()\', and negation with \'!()\'. Example: \'tcp(443), udp(53)\' or \'!(tcp(22), udp(1194))\'
     * @type {string}
     * @memberof ModelsOcservUserConfig
     */
    'restrict-to-ports'?: string;
    /**
     * Allow user access only to defined routes. Example: true
     * @type {boolean}
     * @memberof ModelsOcservUserConfig
     */
    'restrict-to-routes'?: boolean;
    /**
     * Routes pushed to the user for routing traffic. Example: [\'0.0.0.0/0\', \'10.10.0.0/16\']
     * @type {Array<string>}
     * @memberof ModelsOcservUserConfig
     */
    'route'?: Array<string>;
    /**
     * Maximum session time in seconds before forced disconnect. Example: 3600
     * @type {number}
     * @memberof ModelsOcservUserConfig
     */
    'session-timeout'?: number;
    /**
     * List of domains over which the provided DNS servers should be used. Example: [\'example.com\', \'internal.company.com\']
     * @type {Array<string>}
     * @memberof ModelsOcservUserConfig
     */
    'split-dns'?: Array<string>;
}

