/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOcservUserConfig } from './models-ocserv-user-config';

/**
 * 
 * @export
 * @interface OcservUserUpdateOcservUserData
 */
export interface OcservUserUpdateOcservUserData {
    /**
     * 
     * @type {ModelsOcservUserConfig}
     * @memberof OcservUserUpdateOcservUserData
     */
    'config'?: ModelsOcservUserConfig;
    /**
     * 
     * @type {string}
     * @memberof OcservUserUpdateOcservUserData
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcservUserUpdateOcservUserData
     */
    'expire_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcservUserUpdateOcservUserData
     */
    'group'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcservUserUpdateOcservUserData
     */
    'password'?: string;
    /**
     * 10 GiB
     * @type {number}
     * @memberof OcservUserUpdateOcservUserData
     */
    'traffic_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof OcservUserUpdateOcservUserData
     */
    'traffic_type'?: OcservUserUpdateOcservUserDataTrafficTypeEnum;
}

export const OcservUserUpdateOcservUserDataTrafficTypeEnum = {
    FREE: 'Free',
    MONTHLY_TRANSMIT: 'MonthlyTransmit',
    MONTHLY_RECEIVE: 'MonthlyReceive',
    TOTALLY_TRANSMIT: 'TotallyTransmit',
    TOTALLY_RECEIVE: 'TotallyReceive'
} as const;

export type OcservUserUpdateOcservUserDataTrafficTypeEnum = typeof OcservUserUpdateOcservUserDataTrafficTypeEnum[keyof typeof OcservUserUpdateOcservUserDataTrafficTypeEnum];


