/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOcservGroupConfig } from './models-ocserv-group-config';

/**
 * 
 * @export
 * @interface OcservGroupCreateOcservGroupData
 */
export interface OcservGroupCreateOcservGroupData {
    /**
     * 
     * @type {ModelsOcservGroupConfig}
     * @memberof OcservGroupCreateOcservGroupData
     */
    'config': ModelsOcservGroupConfig;
    /**
     * 
     * @type {string}
     * @memberof OcservGroupCreateOcservGroupData
     */
    'name': string;
}

