/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOcservUser } from './models-ocserv-user';
// May contain unused imports in some cases
// @ts-ignore
import type { RequestMeta } from './request-meta';

/**
 * 
 * @export
 * @interface OcservUserOcservUsersResponse
 */
export interface OcservUserOcservUsersResponse {
    /**
     * 
     * @type {RequestMeta}
     * @memberof OcservUserOcservUsersResponse
     */
    'meta': RequestMeta;
    /**
     * 
     * @type {Array<ModelsOcservUser>}
     * @memberof OcservUserOcservUsersResponse
     */
    'result'?: Array<ModelsOcservUser>;
}

