// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/home": {
            "get": {
                "description": "Content of home",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Home"
                ],
                "summary": "Content of home",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/home.HomeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/ocserv/groups": {
            "get": {
                "description": "List of Ocserv groups",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Groups)"
                ],
                "summary": "List of Ocserv groups",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page number, starting from 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to order by",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "Sort order, either ASC or DESC",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ocserv_group.OcservGroupsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            },
            "post": {
                "description": "Ocserv Group creation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Groups)"
                ],
                "summary": "Ocserv Group creation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "ocserv group create data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ocserv_group.CreateOcservGroupData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.OcservGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/ocserv/groups/lookup": {
            "get": {
                "description": "List of Ocserv group names",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Groups)"
                ],
                "summary": "List of Ocserv group names",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/ocserv/groups/{uid}": {
            "delete": {
                "description": "Ocserv Group delete",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Groups)"
                ],
                "summary": "Ocserv Group delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Ocserv Group ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            },
            "patch": {
                "description": "Ocserv Group update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Groups)"
                ],
                "summary": "Ocserv Group update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Ocserv Group ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ocserv group create data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ocserv_group.UpdateOcservGroupData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.OcservGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/ocserv/users": {
            "get": {
                "description": "List of Ocserv Users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Users)"
                ],
                "summary": "List of Ocserv Users",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page number, starting from 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to order by",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "Sort order, either ASC or DESC",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ocserv_user.OcservUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            },
            "post": {
                "description": "Ocserv User creation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Users)"
                ],
                "summary": "Ocserv User creation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "ocserv user create data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ocserv_user.CreateOcservUserData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.OcservUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/ocserv/users/{uid}": {
            "delete": {
                "description": "Ocserv User delete",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Users)"
                ],
                "summary": "Ocserv User delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ocserv User UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            },
            "patch": {
                "description": "Ocserv User update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Users)"
                ],
                "summary": "Ocserv User update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ocserv User UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ocserv user update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ocserv_user.UpdateOcservUserData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.OcservUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/ocserv/users/{uid}/lock": {
            "post": {
                "description": "Ocserv User locking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Users)"
                ],
                "summary": "Ocserv User locking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ocserv User UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/ocserv/users/{uid}/unlock": {
            "post": {
                "description": "Ocserv User unlocking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv(Users)"
                ],
                "summary": "Ocserv User unlocking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ocserv User UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/system": {
            "get": {
                "description": "Get panel System Config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Get panel System Config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.GetSystemResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update panel System Config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Update panel System Config",
                "parameters": [
                    {
                        "description": "update system config data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.PatchSystemUpdateData"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.GetSystemResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/system/init": {
            "get": {
                "description": "Get panel System init Config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Get panel System init Config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.GetSystemInitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/system/setup": {
            "post": {
                "description": "Setup user and system config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Setup user and system config",
                "parameters": [
                    {
                        "description": "system setup data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.SetupSystem"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/system.SetupSystemResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/system/users": {
            "get": {
                "description": "List of Admin or simple users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System(Users)"
                ],
                "summary": "List of Admin or simple users",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page number, starting from 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to order by",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "Sort order, either ASC or DESC",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.UsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middlewares.PermissionDenied"
                        }
                    }
                }
            },
            "post": {
                "description": "Create user Admin or simple",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System(Users)"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "create user data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.CreateUserData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middlewares.PermissionDenied"
                        }
                    }
                }
            }
        },
        "/system/users/login": {
            "post": {
                "description": "Admin users login with Google captcha(captcha site key required in get config api)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System(Users)"
                ],
                "summary": "Admin users login",
                "parameters": [
                    {
                        "description": "login data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.LoginData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/system/users/password": {
            "post": {
                "description": "Change user password by self",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System(Users)"
                ],
                "summary": "Change user password by self",
                "parameters": [
                    {
                        "description": "user new password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.ChangeUserPassword"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.UsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/system/users/profile": {
            "get": {
                "description": "Get User Profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System(Users)"
                ],
                "summary": "Get User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/system/users/{uid}": {
            "delete": {
                "description": "Delete simple user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System(Users)"
                ],
                "summary": "Delete simple user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middlewares.PermissionDenied"
                        }
                    }
                }
            }
        },
        "/system/users/{uid}/password": {
            "post": {
                "description": "Change user password by admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System(Users)"
                ],
                "summary": "Change user password by admin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user new password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.ChangeUserPassword"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.UsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middlewares.PermissionDenied"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "home.HomeResponse": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "online_user": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DailyTraffic"
                    }
                },
                "status": {
                    "$ref": "#/definitions/home.StatsSections"
                }
            }
        },
        "home.StatsSections": {
            "type": "object",
            "required": [
                "current_stats",
                "general_info"
            ],
            "properties": {
                "current_stats": {
                    "type": "string"
                },
                "general_info": {
                    "type": "string"
                }
            }
        },
        "middlewares.PermissionDenied": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "middlewares.Unauthorized": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.DailyTraffic": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "Format: YYYY-MM-DD",
                    "type": "string"
                },
                "rx": {
                    "type": "integer"
                },
                "tx": {
                    "type": "integer"
                }
            }
        },
        "models.OcservGroup": {
            "type": "object",
            "required": [
                "name",
                "uid"
            ],
            "properties": {
                "config": {
                    "description": "or ` + "`" + `type:text` + "`" + ` for wider compatibility",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.OcservGroupConfig"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.OcservGroupConfig": {
            "type": "object",
            "properties": {
                "cgroup": {
                    "description": "Linux control group to assign the VPN worker process to. Format: 'controller,subsystem:name'. Example: 'cpuset,cpu:test'",
                    "type": "string"
                },
                "deny-roaming": {
                    "description": "Disconnect client if its IP changes (e.g., due to network switch). Example: true",
                    "type": "boolean"
                },
                "dns": {
                    "description": "Comma-separated list of DNS servers to assign to the client. Example: '8.8.8.8,1.1.1.1'",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dpd": {
                    "description": "Dead Peer Detection timeout in seconds. Example: 90",
                    "type": "integer"
                },
                "explicit-ipv4": {
                    "description": "Static IPv4 address to assign to client. Example: '192.168.100.10'",
                    "type": "string"
                },
                "idle-timeout": {
                    "description": "Time in seconds before disconnecting idle clients. Example: 600",
                    "type": "integer"
                },
                "ipv4-network": {
                    "description": "The pool of addresses that leases will be given from. Example: '192.168.1.0/24'",
                    "type": "string"
                },
                "iroute": {
                    "description": "Internal route available only via VPN. Format: 'IP/prefix'. Example: '10.0.0.0/8'",
                    "type": "string"
                },
                "keepalive": {
                    "description": "Interval in seconds to send keep-alive pings. Example: 60",
                    "type": "integer"
                },
                "max-same-clients": {
                    "description": "Maximum simultaneous logins per user. Example: 2",
                    "type": "integer"
                },
                "mobile-dpd": {
                    "description": "DPD timeout specifically for mobile clients. Example: 300",
                    "type": "integer"
                },
                "mobile-idle-timeout": {
                    "description": "Idle timeout for mobile clients. Example: 900",
                    "type": "integer"
                },
                "mtu": {
                    "description": "Tunnel interface MTU to avoid fragmentation. Example: 1400",
                    "type": "integer"
                },
                "nbns": {
                    "description": "NetBIOS Name Servers (WINS) for Windows clients. Example: '192.168.1.1'",
                    "type": "string"
                },
                "net-priority": {
                    "description": "Priority for routes; lower is higher priority. Example: 1",
                    "type": "integer"
                },
                "no-route": {
                    "description": "List of networks to exclude from VPN routing. Each entry should be in 'IP/prefix' format. Example: ['192.168.0.0/16', '10.0.0.0/8']",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "no-udp": {
                    "description": "Disables UDP, enforcing TCP-only VPN connection. Example: true",
                    "type": "boolean"
                },
                "restrict-user-to-ports": {
                    "description": "Comma-separated list of allowed (or blocked, if negated) protocols and ports. Supports 'tcp(port)', 'udp(port)', 'icmp()', 'icmpv6()', and negation with '!()'. Example: 'tcp(443), tcp(80), udp(53)', or '!(tcp(22), udp(1194))'",
                    "type": "string"
                },
                "restrict-user-to-routes": {
                    "description": "Allow client access only to defined routes. Example: true",
                    "type": "boolean"
                },
                "route": {
                    "description": "Routes pushed to the client for routing traffic. Example: ['0.0.0.0/0', '10.10.0.0/16']",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rx-data-per-sec": {
                    "description": "Maximum receive bandwidth in bytes per second. Example: '100000' for 100 KB/s",
                    "type": "integer"
                },
                "session-timeout": {
                    "description": "Max session time in seconds before forced disconnect. Example: 3600",
                    "type": "integer"
                },
                "split-dns": {
                    "description": "List of domains over which the provided DNS servers should be used. Example: ['example.com', 'internal.company.com']",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stats-report-time": {
                    "description": "Interval in seconds for stats reporting. Example: 300",
                    "type": "integer"
                },
                "tunnel-all-dns": {
                    "description": "Force all DNS traffic through the VPN tunnel. Example: true",
                    "type": "boolean"
                },
                "tx-data-per-sec": {
                    "description": "Maximum transmit bandwidth in bytes per second. Example: '200000' for 200 KB/s",
                    "type": "integer"
                }
            }
        },
        "models.OcservUser": {
            "type": "object",
            "required": [
                "created_at",
                "group",
                "is_locked",
                "is_online",
                "password",
                "rx",
                "traffic_size",
                "traffic_type",
                "tx",
                "uid",
                "username"
            ],
            "properties": {
                "config": {
                    "$ref": "#/definitions/models.OcservUserConfig"
                },
                "created_at": {
                    "type": "string"
                },
                "deactivated_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "expire_at": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "is_locked": {
                    "type": "boolean"
                },
                "is_online": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "rx": {
                    "description": "Receive in bytes",
                    "type": "integer"
                },
                "traffic_size": {
                    "description": "in GiB  \u003e\u003e x * 1024 ** 3",
                    "type": "integer"
                },
                "traffic_type": {
                    "type": "string",
                    "enum": [
                        "Free",
                        "MonthlyTransmit",
                        "MonthlyReceive",
                        "TotallyTransmit",
                        "TotallyReceive"
                    ]
                },
                "tx": {
                    "description": "Transmit in bytes",
                    "type": "integer"
                },
                "uid": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.OcservUserConfig": {
            "type": "object",
            "properties": {
                "banner": {
                    "description": "Text message shown to users when they connect to the VPN. Example: 'Welcome to the company VPN!'",
                    "type": "string"
                },
                "dns": {
                    "description": "Comma-separated list of DNS servers to assign to the user. Example: '8.8.8.8,1.1.1.1'",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "explicit_ipv4": {
                    "description": "Static IPv4 address to assign to the user. Example: '192.168.100.10'",
                    "type": "string"
                },
                "idle_timeout": {
                    "description": "Time in seconds before disconnecting idle users. Example: 600",
                    "type": "integer"
                },
                "ipv4_network": {
                    "description": "The pool of addresses from which to assign to the user. Example: '192.168.1.0/24'",
                    "type": "string"
                },
                "iroute": {
                    "description": "Internal route available only via VPN. Example: '10.0.0.0/8'",
                    "type": "string"
                },
                "mobile_idle_timeout": {
                    "description": "Idle timeout in seconds for mobile users. Example: 900",
                    "type": "integer"
                },
                "nbns": {
                    "description": "NetBIOS Name Servers (WINS) for Windows clients. Example: '192.168.1.1'",
                    "type": "string"
                },
                "no_route": {
                    "description": "List of networks to exclude from VPN routing. Example: ['192.168.0.0/16', '10.0.0.0/8']",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rekey_time": {
                    "description": "Rekey time in seconds; triggers key renegotiation. Example: 86400 for 24 hours",
                    "type": "integer"
                },
                "restrict_to_ports": {
                    "description": "Comma-separated list of allowed or blocked ports/protocols. Supports 'tcp(port)', 'udp(port)', 'icmp()', 'icmpv6()', and negation with '!()'. Example: 'tcp(443), udp(53)' or '!(tcp(22), udp(1194))'",
                    "type": "string"
                },
                "restrict_to_routes": {
                    "description": "Allow user access only to defined routes. Example: true",
                    "type": "boolean"
                },
                "route": {
                    "description": "Routes pushed to the user for routing traffic. Example: ['0.0.0.0/0', '10.10.0.0/16']",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "session_timeout": {
                    "description": "Maximum session time in seconds before forced disconnect. Example: 3600",
                    "type": "integer"
                },
                "split_dns": {
                    "description": "List of domains over which the provided DNS servers should be used. Example: ['example.com', 'internal.company.com']",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.System": {
            "type": "object",
            "properties": {
                "_": {
                    "type": "integer"
                },
                "google_captcha_secret": {
                    "type": "string"
                },
                "google_captcha_site_key": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "_",
                "is_admin",
                "uid",
                "username"
            ],
            "properties": {
                "_": {
                    "type": "integer"
                },
                "createdAt": {
                    "description": "LastLogin *time.Time ` + "`" + `json:\"last_login\"  validate:\"required\"` + "`" + `",
                    "type": "string"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "ocserv_group.CreateOcservGroupData": {
            "type": "object",
            "required": [
                "config",
                "name"
            ],
            "properties": {
                "config": {
                    "$ref": "#/definitions/models.OcservGroupConfig"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "ocserv_group.OcservGroupsResponse": {
            "type": "object",
            "required": [
                "meta"
            ],
            "properties": {
                "meta": {
                    "$ref": "#/definitions/request.Meta"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OcservGroup"
                    }
                }
            }
        },
        "ocserv_group.UpdateOcservGroupData": {
            "type": "object",
            "required": [
                "config"
            ],
            "properties": {
                "config": {
                    "$ref": "#/definitions/models.OcservGroupConfig"
                }
            }
        },
        "ocserv_user.CreateOcservUserData": {
            "type": "object",
            "required": [
                "group",
                "password",
                "traffic_type",
                "username"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1024,
                    "example": "User for testing VPN access"
                },
                "expire_at": {
                    "type": "string",
                    "example": "2025-12-31"
                },
                "group": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 2
                },
                "traffic_size": {
                    "description": "10 GiB",
                    "type": "integer",
                    "minimum": 0,
                    "example": 10737418240
                },
                "traffic_type": {
                    "type": "string",
                    "enum": [
                        "Free",
                        "MonthlyTransmit",
                        "MonthlyReceive",
                        "TotallyTransmit",
                        "TotallyReceive"
                    ],
                    "example": "MonthlyTransmit"
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 2
                }
            }
        },
        "ocserv_user.OcservUsersResponse": {
            "type": "object",
            "required": [
                "meta"
            ],
            "properties": {
                "meta": {
                    "$ref": "#/definitions/request.Meta"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OcservUser"
                    }
                }
            }
        },
        "ocserv_user.UpdateOcservUserData": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1024,
                    "example": "User for testing VPN access"
                },
                "expire_at": {
                    "type": "string",
                    "example": "2025-12-31"
                },
                "group": {
                    "type": "string",
                    "example": "default"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "strongpassword123"
                },
                "traffic_size": {
                    "description": "10 GiB",
                    "type": "integer",
                    "example": 10737418240
                },
                "traffic_type": {
                    "type": "string",
                    "enum": [
                        "Free",
                        "MonthlyTransmit",
                        "MonthlyReceive",
                        "TotallyTransmit",
                        "TotallyReceive"
                    ],
                    "example": "MonthlyTransmit"
                }
            }
        },
        "request.ErrorResponse": {
            "type": "object",
            "required": [
                "error",
                "message"
            ],
            "properties": {
                "error": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "request.Meta": {
            "type": "object",
            "required": [
                "page",
                "page_size",
                "total_records"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "system.ChangeUserPassword": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "system.CreateUserData": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "admin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "system.GetSystemInitResponse": {
            "type": "object",
            "properties": {
                "google_captcha_site_key": {
                    "type": "string"
                }
            }
        },
        "system.GetSystemResponse": {
            "type": "object",
            "properties": {
                "google_captcha_secret_key": {
                    "type": "string"
                },
                "google_captcha_site_key": {
                    "type": "string"
                }
            }
        },
        "system.LoginData": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 2,
                    "example": "doe123456"
                },
                "remember_me": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 2,
                    "example": "john_doe"
                }
            }
        },
        "system.PatchSystemUpdateData": {
            "type": "object",
            "required": [
                "google_captcha_secret_key",
                "google_captcha_site_key"
            ],
            "properties": {
                "google_captcha_secret_key": {
                    "type": "string"
                },
                "google_captcha_site_key": {
                    "type": "string"
                }
            }
        },
        "system.SetupSystem": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "google_captcha_secret_key": {
                    "type": "string"
                },
                "google_captcha_site_key": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 4
                },
                "username": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 2
                }
            }
        },
        "system.SetupSystemResponse": {
            "type": "object",
            "required": [
                "system",
                "token",
                "user"
            ],
            "properties": {
                "system": {
                    "$ref": "#/definitions/models.System"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "system.UserLoginResponse": {
            "type": "object",
            "required": [
                "token",
                "user"
            ],
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "system.UsersResponse": {
            "type": "object",
            "required": [
                "meta"
            ],
            "properties": {
                "meta": {
                    "$ref": "#/definitions/request.Meta"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Ocserv User management Example Api",
	Description:      "This is a sample Ocserv User management Api server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
