// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OcOcctlApiRepositoryInterface is an autogenerated mock type for the OcOcctlApiRepositoryInterface type
type OcOcctlApiRepositoryInterface struct {
	mock.Mock
}

// Stats provides a mock function with given fields: ctx
func (_m *OcOcctlApiRepositoryInterface) Stats(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOcOcctlApiRepositoryInterface creates a new instance of OcOcctlApiRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOcOcctlApiRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OcOcctlApiRepositoryInterface {
	mock := &OcOcctlApiRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
